### ISSUE TITLE
Highlight geocoded location

### ISSUE THREAD

**Issue by liberostelios** [tudelft3d/3dbag-viewer#13]
I think it would be cool if we could highlight the selected geocoded location, instead of just moving there.

It takes a few moments for the user to locate themselves around the area and identify the object they might be looking for, even if they are pretty comfortable with the geometry of the area (I checked with my neighbourhood). It would be nice if we could have some kind of arrow or cylinder to point to the location of the picked location for a few seconds after the camera moves there.

**Comment by Ylannl** [comment]
this was implemented by @jliempt
