### ISSUE TITLE
Revamp UI

### ISSUE THREAD

**Issue by liberostelios** [tudelft3d/3dbag-viewer#14]
We need to change the UI to something nicer and remove debug information.

- [x] add tabs for Documentation, Terms of use
- [x] global navigation (sidebar)
- [x] incorporate static content (pages) somehow
- [x] toggle between LoDs and basemaps
- [x] allow building picking on mobile (with touch events, double tap?)
- [x] 2D map tile download page
- [x] link to attribute documentation from building info panel
- [x] complete attribution on map (incl for base layer)
- [x] start in Delft

**Comment by Ylannl** [comment]
I can look into this.
