### ISSUE TITLE
WMTS delayed tile loading

### ISSUE THREAD

**Issue by Ylannl** [tudelft3d/3dbag-viewer#20]
In some cases, eg when you pan around and zoom a lot, the WMTSTilesRenderer seems to be doing more downloads than necessary (ie because the we already moved on to a different view/zoom level). Then it can happen that there is a delay of minutes before the tiles in the current view show up, since it first has to complete all the unnecessary downloads.

**Comment by liberostelios** [comment]
51fc455 partially tackles this issue. But a more permanent solution might be better.

**Comment by Ylannl** [comment]
e751d0f5a24584652d135cf935fa3d729f1ef0db fixes this by tile aborting pending downloads for tiles that are no long in the camera frustum.

**Comment by Ylannl** [comment]
This now lives in the branch: https://github.com/tudelft3d/3dbag-viewer/tree/feature/wmts-abort-download .

It works, but the textures don't show in Safari and Firefox.
