### ISSUE TITLE
Terrain-tiles: Elminate white flashes when switching between matrix levels.

### ISSUE THREAD

**Issue by Ylannl** [tudelft3d/3dbag-viewer#26]
This occurs especially when zooming in and out.

Inspiration: https://stackoverflow.com/questions/12666570/how-to-change-the-zorder-of-object-with-threejs

**Comment by jliempt** [comment]
Fixed this by overlapping tiles from different `tileLevel`, making use of `renderOrder`. White tiles are rendered first, then tiles from the old `tileLevel`, and lastly new tiles. This means that the most relevant tile is rendered last and thus on top. With `depthWrite = false` you prevent artefacts showing up on overlapping geometries. Tiles from old `tileLevel` are removed from memory when `downloadQueue` is empty.
