### ISSUE TITLE
Ability to download subset of data or link to the 2D viewer for that

### ISSUE THREAD

**Issue by liberostelios** [tudelft3d/3dbag-viewer#3]
Currently its only possible to download the cityjson files, but there are several formats available.

See comments in https://github.com/tudelft3d/3dbag-viewer/issues/50

**Comment by Ylannl** [comment]
I started to work on this issue, see dd12ebb.

The bulk of the work is done. What is left:

- [ ] put the 2D tile selection map on the same coordinates as the 3D viewer
- [ ] store selected Tile ID as a URL parameters
- [ ] generate the proper download URL's and other metadata (filesize, MD5)
- [ ] update text descriptions for each download form

**Comment by Ylannl** [comment]
Should also add a geocoder, see https://github.com/jonataswalker/ol-geocoder.

**Comment by liberostelios** [comment]
1371be6 is related to this.

**Comment by Ylannl** [comment]
Future work is described in #57 (2d download map) and #59 (files metadata)
