### ISSUE TITLE
Button to set view towards north

### ISSUE THREAD

**Issue by Ylannl** [tudelft3d/3dbag-viewer#37]
I'm regularly getting confused about where is the north while navigating the 3D viewer. I propose we add a button that points the camera towards the north.

**Comment by hugoledoux** [comment]
and also perform a North arrow?

**Comment by jliempt** [comment]
Functionality is finished, @Ylannl will find or design a better button.

**Comment by Ylannl** [comment]
Finished with 63e0927471262547b4d6066fe71df198ee2e1003
