### ISSUE TITLE
Do not reload basmap when switching lod

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dbag-viewer#45]
When switching to previously unselected (or removed from the cache) lod-s, than also the basemap reload. I think the basemap should be kept.

Eg at https://godzilla.bk.tudelft.nl/3dbag-viewer/#/en/viewer?rdx=98900.09516101495&rdy=441408.3974558625&ox=-3751.6210423837183&oy=4722.956116911304&oz=-3094.1077607110765

**Comment by jliempt** [comment]
See #46, cause by same issue.
