### ISSUE TITLE
Render before tileset is parsed

### ISSUE THREAD

**Issue by liberostelios** [tudelft3d/3dbag-viewer#5]
- [ ] Render when tileset is parsed (to start the rendering loop if first request is slow)

**Comment by liberostelios** [comment]
I assume you mean that we should render things like the terrain?

**Comment by Ylannl** [comment]
hmm, now that I read this again, I think the issue you mentioned here originally is already solved with the improvements from the NASA guy?

**Comment by liberostelios** [comment]
Yes, indeed. I thought you meant that this was for the terrain (WMS/WMTS) when it becomes decoupled from the tiles renderer.

**Comment by Ylannl** [comment]
Alright then I will just close this issue. But indeed we should also not block rendering of the terrain while the tileset is still loaded.
