### ISSUE TITLE
Implement download per format

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dbag-viewer#50]
Currently its only possible to download the cityjson files, but there are several formats available.

**Comment by Ylannl** [comment]
For this the 2D download page has to be extended. One thing we'll have to agree on are the download URLs, I propose something like:

`3dbag.nl/download/VERSION/FORMAT/TILE_ID.EXTENSION`

**Comment by balazsdukai** [comment]
Except for the postgres dowloads, where we have a single file per version.


`3dbag.nl/download/VERSION/FORMAT/bag3d_VERSION.EXT`

Or this in general:

`3dbag.nl/download/VERSION/FORMAT/bag3d_VERSION_TILE-ID.EXTENSION`

**Comment by balazsdukai** [comment]
Plus probably a good idea to add a 'latest' subpath that points to the latest version:

`3dbag.nl/download/latest/FORMAT/bag3d_VERSION_TILE-ID.EXTENSION`
