### ISSUE TITLE
North arrow animation (disable when already looking north)

### ISSUE THREAD

**Issue by jliempt** [tudelft3d/3dbag-viewer#65]
Currently, the camera rotates for a fixed amount of time when you click the arrow, regardless of the initial orientation. 

The animation should at least be disabled when it's already oriented to the north, since if you then click it you won't see anything happening, but the animation will still mess with the controls during that period.

**Comment by liberostelios** [comment]
Why not make the rotation duration relative to the angle to the north, when clicking the button? It makes more sense to me.

**Comment by jliempt** [comment]
Yes, that would be optimal. 👍
