### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by ondrej-vesely** [tudelft3d/3dbag-viewer#76]
The repo is missing a license file.
Under which license is the viewer source code available?

All I could find is in the documentation on [https://docs.3dbag.nl/en/copyright/](https://docs.3dbag.nl/en/copyright/)
"Our viewer relies on 3DTilesRendererJS (Apache) by NASA AMMOS and pg2b3dm (MIT) by Geodan."

**Comment by Ylannl** [comment]
Hi Ondrej. You can use the code under the GPL v3 license. I just added a license file.
