### ISSUE TITLE
Showing custom 3D tileset

### ISSUE THREAD

**Issue by dennisfrijlink** [tudelft3d/3dbag-viewer#77]
Hi there,

At the moment we're working on a school project using the 3DBag viewer. Our goal is to show a specific set of buildings based on their IMBAG ID instead of showing **all** buildings. So for example, we don't wanna show `NL.IMBAG.Pand.0344100000039864` but do show `NL.IMBAG.Pand.0344100000027112`.  

The set of IMBAG ID's we want to show is ready to go! So the only question is, "How do we filter the buildings shown in the 3D bagviewer based on their IMBAG ID? (or "identifactie" called in NL)".

Thanks in advance.

**Comment by dennisfrijlink** [comment]
The goal is to create a custom tileset based on the buildings we have identified.

**Comment by dennisfrijlink** [comment]
Small question, do you load all (3D) buildings at load time or while going over the map?

**Comment by balazsdukai** [comment]
> Small question, do you load all (3D) buildings at load time or while going over the map?

They are loaded tile-by-tile while going over the map.

**Comment by dennisfrijlink** [comment]
Is it possible to show a specific list of buildings (based on their IMBAG ID)?

**Comment by dennisfrijlink** [comment]
I have a collection of specific IMBAG ID's that I wanna show. Is it very difficult to create a custom tileset and what do I need for that?

And if that is way too difficult how can I hide a specific selection that is already loaded based on their IMBAG ID's?

**Comment by dennisfrijlink** [comment]
You have a data dump of the 3D BAG Data (https://data.3dbag.nl/postgres/3dbag_v21031_7425c21b.zip).
Is it possible to create a custom tileset from that with the specific buildings we wanna show?

**Comment by balazsdukai** [comment]
See https://github.com/tudelft3d/3dbag-viewer/issues/78 .
I'm closing this issue, because the original question was answered.
