### ISSUE TITLE
Create custom tileset

### ISSUE THREAD

**Issue by dennisfrijlink** [tudelft3d/3dbag-viewer#78]
Hi there,

In your code you load specific tilesets that you've create by your own. The question is how to create my own tileset (based on the IMAG ID's I want)?

**Comment by balazsdukai** [comment]
We use this https://github.com/tudelft3d/pg2b3dm for exporting to 3D tiles, you are free to try it and use it.
I'm closing this issue because it is not related to the viewer, but it is about the data that the viewer displays.
